### ISSUE TITLE
Write up challenges of work done for blog

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/ExternalServiceAggregator#2]
Eg.

* pros / cons of micro services
* CI & continuous delivery with Travis CI & Dokku

**Comment by simoncasey** [comment]
- handling deployment of maven artifacts without a public repository (thank you jitpack.io!)

**Comment by simoncasey** [comment]
- issues with missing ssl certificates in Java keystore (travis CI in particular)

**Comment by eddiejaoude** [comment]
Might be worth moving this issue to the Blog repo?

**Comment by simoncasey** [comment]
Moved to blog issues

**Comment by eddiejaoude** [comment]
:+1:
